AppBundle\Entity\Astuce:
    type: entity
    table: astuce
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        details:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        videoUrl:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: video_url
    lifecycleCallbacks: {  }
