AppBundle\Entity\Benificiare:
    type: entity
    table: benificiare
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        adresse:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        age:
            type: integer
            nullable: false
            options:
                unsigned: false
        typeAide:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: type_aide
    lifecycleCallbacks: {  }
