AppBundle\Entity\Commentaire:
    type: entity
    table: commentaire
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idBlog:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_blog
        comment:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        idUtilisateur:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_utilisateur
        date:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
