AppBundle\Entity\Declaration:
    type: entity
    table: declaration
    id:
        idDeclaration:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_Declaration
            generator:
                strategy: IDENTITY
    fields:
        sujet:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lieu:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        date:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        etat:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: 'non lu'
        action:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: 'non traité'
        photo:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
