AppBundle\Entity\Enchere:
    type: entity
    table: enchere
    indexes:
        produit:
            columns:
                - id_produit
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idProduit:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_produit
        prixInitial:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: prix_initial
        acheteur:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        !!binary cHJpeEluY3LjqW1lbnTjqQ==:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: 'prix incrémenté'
        dateEnchere:
            type: date
            nullable: false
            column: date_enchere
    lifecycleCallbacks: {  }
