AppBundle\Entity\Event:
    type: entity
    table: event
    id:
        idEvent:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_Event
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        date:
            type: date
            nullable: false
        lieu:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        nbInterresse:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: nb_interresse
        nbMax:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: nb_max
        photo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        nbParticipant:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: nb_participant
        idAssociation:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_association
    lifecycleCallbacks: {  }
