AppBundle\Entity\HistoriqueEvent:
    type: entity
    table: historique_event
    id:
        idEvent:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_Event
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        date:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lieu:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nbInterresse:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nb_interresse
        nbMax:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nb_max
        nbParticipant:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nb_participant
    lifecycleCallbacks: {  }
