AppBundle\Entity\Historique:
    type: entity
    table: historique
    id:
        idDeclaration:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_declaration
            generator:
                strategy: IDENTITY
    fields:
        sujet:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        lieu:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        date:
            type: date
            nullable: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        etat:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        action:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        photo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
