AppBundle\Entity\Historiqueusers:
    type: entity
    table: historiqueusers
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: first_name
        name:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        birthDate:
            type: date
            nullable: false
            column: birth_date
        phone:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        mail:
            type: string
            nullable: false
            length: 35
            options:
                fixed: false
        adress:
            type: string
            nullable: false
            length: 35
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
                default: descrition
        role:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
    lifecycleCallbacks: {  }
