AppBundle\Entity\Participant:
    type: entity
    table: participant
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: first_name
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        birthDate:
            type: date
            nullable: false
            column: birth_date
        phone:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        mail:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        adress:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        idEvent:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_Event
    lifecycleCallbacks: {  }
